import { CardType } from "./cards.dto"

const defaultCard: CardType = {
   id: 0,
   name: "Random card",
   title: "Unknown title",
   lvl: 1,
   coins: 1,
   coinsInHour: 10,
   description: "Купи меня",
   image: "https://via.placeholder.com/150",
   color: "#000",
   variant: "default",
 }

 
export const cards: CardType[] = [
   {
     id: 1,
     name: "Tea break master",
     title: "ХаудиХо",
     lvl: 3,
     coins: 19,
     coinsInHour: 199,
     description: "Купи меня",
     image: "https://via.placeholder.com/150",
     color: "#000",
     variant: "default",
   },
   {
     id: 2,
     name: "Tea break master",
     title: "Marmok",
     lvl: 5,
     coins: 19,
     coinsInHour: 311,
     description: "Описание карточки 2",
     image: "https://via.placeholder.com/150",
     color: "#000",
     variant: "new",
   },
   {
      id: 3,
     name: "Bloger break master",
     title: "EeOneGuy",
     lvl: 1,
     coins: 39,
     coinsInHour: 441,
     description: "Описание карточки 3",
     image: "https://via.placeholder.com/150",
     color: "#000",
     variant: "approved",
   },
   {
     ...defaultCard,
     id: 4,
     name: "Tea break master",
     lvl: 3,
     coins: 19,
     coinsInHour: 199,
     description: "Описание карточки 4",
     image: "https://via.placeholder.com/150",
     color: "#000",
     variant: "default",
   },
   {
     ...defaultCard,
     id: 5,
     name: "Tea break master",
     lvl: 3,
     coins: 19,
     coinsInHour: 199,
     description: "Описание карточки 5",
     image: "https://via.placeholder.com/150",
     color: "#000",
     variant: "new",
   },
   {
     ...defaultCard,
     id: 6,
     name: "Tea break master",
     lvl: 3,
     coins: 19,
     coinsInHour: 199,
     description: "Описание карточки 6",
     image: "https://via.placeholder.com/150",
     color: "#000",
     variant: "new",
   },
   {
     ...defaultCard,
     id: 7,
     name: "Tea break master",
   },
 ]